export const ANIMATED_CHECK_DRAW_DURATION = 0.5;
export const ANIMATED_CHECK_HOLD_DURATION = 0.7;
export const ANIMATED_CHECK_UNCHECK_DURATION = 0.3;
export const ANIMATED_CHECK_PAUSE_DURATION = 0.5;
export const ANIMATED_CHECK_ITEM_COUNT = 3;
export const ANIMATED_CHECK_CYCLE_DURATION =
  ANIMATED_CHECK_ITEM_COUNT * ANIMATED_CHECK_DRAW_DURATION +
  ANIMATED_CHECK_HOLD_DURATION +
  ANIMATED_CHECK_UNCHECK_DURATION +
  ANIMATED_CHECK_PAUSE_DURATION;
